### ISSUE TITLE
link to the neural network weights 

### ISSUE THREAD

**Issue by ziyewang** [nafizh/TRAC#1]
Dear Hamid,

I am interested in the work, but the link for the neural network weights seems to be lost. Could I obtain the files of the neural network weights?

Best,
Ziye

**Comment by nafizh** [comment]
Hi Ziye, sorry I didn't receive a notification for this issue. I have fixed the link.
Here is the new link -

https://www.dropbox.com/sh/6og83rydevqsr3y/AACiSBDPuueEKx8eaV8Rzo3_a?dl=0

**Comment by ziyewang** [comment]
Thanks.
