### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by TahaAslani** [nafizh/TRAC#2]
Hi,

I am trying to install and run your model, but it is giving me this error:

"FileNotFoundError: [Errno 2] No such file or directory: 'weights_TRAC/models/learn_model_for_loop_fold_1.pth'"

I have already downloaded the weights data; however, this file did not exist in the dropbox folder. Please advise.

Thanks.

**Comment by nafizh** [comment]
Hi, sorry, I am not getting any notification when an issue opens up. Was your problem solved? In the trac.py file,  you can just replace 'learn_model_for_loop_fold_%d' with  'learn_model_cd_hit_0_7_for_loop_fold_%d_label_smoothing_all_freeze.pth' and it should solve the problem.

**Comment by nafizh** [comment]
I have also updated the code, so you can now download the new trac.py file, and it should work. If it still doesn't work, let me know.

**Comment by TahaAslani** [comment]
Hi Nafiz!
No worries. This solved the problem. Thanks!
